### ISSUE TITLE
about applying your work to multi-label classification

### ISSUE THREAD

**Issue by yuanyuansiyuan** [chrislybaer/Powerset-CNN#1]
Hi, i have read your paper and i wonder that can i apply your work to the multi-label classification scenario? where each sample has a multi-hot label, which is actually one of the power set labels in size 2^N(N is the class number).

Hope for your response, thank you~

**Comment by wendlerc** [comment]
In the current implementation only the inputs are indexed by a powerset. It might be possible to leverage set function signal processing [1] to facilitate multi-label classification, e.g., when there are limited interactions between the class labels. However, I did not think about that yet.

Kind regards,
Chris 

[1] https://acl.inf.ethz.ch/publications/icassp18-setfcts.pdf

**Comment by wendlerc** [comment]
I know some time has passed by now... But, I looked at muti-label classification again and I am pretty sure now that one could try to put my powerset CNN on top of a multi-label NN to refine its outputs.
